# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

# =======================================#
# -----------BASE SETTINGS---------------#
#========================================#

title: Dumbarton 
email: 
description: a minimalistic jekyll theme for academics
baseurl:                                       # the subpath of your site, e.g. /blog
url: "https://dumbarton.netlify.app/"          # the base hostname & protocol for your site, e.g. http://example.com
image: /assets/img/dumbarton.png               # used to generate site link preview
image_alt: A minimalistic jekyll theme for academic    # image description

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#: 
author: John Doe 
profile_image: /assets/img/avatar/cropped.png #/assets/img/avatar/avatar.jpeg 
occupation: 
snippet:
twitter: tbutler0x90
github: tcbutler320
linkedin: tyler-b-a700a1aa
stackoverflow: '12935605'
website: https://tbutler.org
codepen: 
medium: 
email: developer.tbutler@gmail.com
keybase: tbutler320
pgp: 
ctftime: 
phonenumber: 

#========================================#
# --------- UI THEMES -------------------#
#========================================#
ui_theme: abyss                                 # Create your own theme by setting options in _data/themes.yml


# =======================================#
# -----------BLOG SETTINGS---------------#
#========================================#

tags:  post jekyll styleguide ipsum
twitter-widget: false # true,false                  # Used to show your twitter timeline on blog home page

comments: false                                     # Used to enable comments on blog posts
gitalk_client_id:             
gitalk_client_secret:    
gitalk_repo:
gitalk_owner: 
gitalk_admin: 
gitalk_distraction_mode: false

# =======================================#
# -----------THEME SETTINGS--------------#
#========================================#

nav-color: "#00334e"                                 # options: light, dark, transparent, primary, custom | Change the color of the navbar
footer-color: "#00334e"
color-scheme: "#00334e"                              # options: demo | changes color scheme based on preset values 
card-color: "#00334e"                                # Used on cards like the home highlights section
nav-dIcon: "fas fa-caret-down"                       # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
animate: true                                        # false or true, uses animate.css to animate certain functions

# =======================================#
# -----------HOME PAGE  SETTINGS --------#
#========================================#
home_option: education                               # options: education, skills, timeline

# =======================================#          # These  settings are for demo purposes only, things like 
# -----------HELP SETTINGS---------------#          #     popup toasts and tooltips designed to help new 
#========================================#          #     developers as they look into using this theme      
help_tips: false                                    # options: true, false  | use false to disable these for production mode


# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-environment-variables
sass:
  sass_dir: _sass
  style: compressed


include:
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Dumbarton
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
font_awesome_id: 32a2b2a489                       # Register for free at https://fontawesome.com/ to get your id


# =======================================#        # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
google-site-verification:                         #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                              #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                       # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                    # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                           #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                                   # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                                  # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                        # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                          # Facebook OpenGraph 




pgp-key: "-----BEGIN PGP PUBLIC KEY BLOCK-----
mQINBF8SaxABEACxPxrYnHj8RlC7d1DyZDdlNREADaAEJDvWmILBWE4aYVOVyxSA
yQ3gXYaOb0zoDR8r1tLtvDVfBtQKEK8KQWN8ZFQI/PAj2FVMtnqncFyIEwKXVOXO
sgC3VKJBUvMXDChInXVUa4vs8varqLneTmAYi16bloLS1zL9Z7S CILbjSTUOyCz
gmum8ea0IqFCqD8Lg2MSiWRax6F2HI/4RepgPCxzs51EhEkTMG80U3H8VxRlmpA5
1gmUkhNaHSFujPPHI0k6ArnIrDiz/ouV3kESfGxDaOKedPZmxeWQtl7S2HEKXPrN
ugeg1l8ny7Gh vIDnfbAjhMjHD0t0dXcW2lc77Le8IyXWfCqvAJvuB0DImV039KL
cLRzbDa19L2C0dFTy2eKSyQOiQwhyu1JoxVW oLYeyCuL0Ptl4LRnlLbH9iYwCCs
lx1piJ0YSDoSS2XJULNssJUO7wAejXua8t41gWuYqWZW1IE4Bvcox0H3sFh8tDG/
jhJBg5E2Lwkg7LOWlBB9QFcnKk0qrIFZ2vtWUfrqr22iU7mStJ8b46Gttra8Nywl
6rk0v/tPzMRwi3uHSCbcfzWgKOy8AyRI1Bwj9xAq7r9lYUe/eEXZeQMfJEYhq3Fu
c3xVhMjKQO6r4Y2hmDmEesKHvOkKQ0q lY jt4zKUrXfQj0ebUtcqBtbWwARAQAB
tCRUeWxlciBCdXRsZXIgPHRjYnV0bGVyMzIwQGdtYWlsLmNvbT6JAlQEEwEIAD4W
IQTIZh5ulP tFioqo3V1ojT/iPmcGgUCXxJrEAIbAwUJB4YfgAULCQgHAgYVCgkI
CwIEFgIDAQIeAQIXgAAKCRB1ojT/iPmcGi6XEACZPnJwRTSLesAows E gjIAk3E
KQPCBjpH3XHln6SYNk3yy7RG6mNjYf5r6I2lfvcpbyvnuNszk/Am0Q2buU/ncEe/
kAS2rtqeDkmroPwuE nWz/v /8uujsHujgS9xJngljGVNecFfjkENvAh4j163LPz
iySahEbM6praHAZBQhC5lHpBi rrnOUk/q5Uk5kIfMvRWKVqAYARyMkyc6yy5chd
JGsDtx51h62j1MxyrHFCxJ319iNh5EEKhEeyu7jfM2jWAp/PA eMfj7jAnhJeQJ0
30Wrohg6LXnM7l2P12EY 9rcctIhe2xvM1nHhnqm8kiNCXHF3M755uhCxY4pygT4
zM2UatcY3fFXlkvOvkFaLgTwD9scJZVnTM jo0m9/HjuXVsVr4IDmKFBWX5HhjAA
ySXMObjuqXScy4mEg0QvfBSQsv40sVadWAGnsa5SHIXnSn8T22jNyiH7QhMG3LVr
duAiXSWHs Y1FsTrV2J43fmG5Y/ZgbOitQPMQWft7SRoR4uqGBLA7z2xC2WSgHzt
Vz EFvykiaX6LOpPo79Pt nx5DDMPhXucxHBdYcxl7wyD6CbU4vz/Nd5c0ZMdMXb
eMAZ77LvmhPZOs7fbpJwKJAbviyc1b8M5SQir1s7cUfRcUSBmYoWHn55wO7bLmrt
uAlOeI3W2K7e3/J LbkCDQRfEmsQARAAx9zAyPT3RMrr38Rz9sPaJoL8eVCf5rio
xokBE7iBDl3r jDfLLFQX7nDkNwqAg vfVB6X0uL1JMokq0F4xoBjcz56eF9p4dG
V5QieTLJsVz5glQ2jLkt/D7Sqi6AWi9vDT/w2EuKTHsE30Kp0kOLirEXhc 2h8Dv
3P/TcJ8Rjl2W6QqFytQbkxulbe/PkHge75RNz/vG7jv859VRUX0XrYTC4iQGiAGj
F0LW uVdX8cTTutmrvM yhY53Nk8/NRHYjOeF4fIomxX67EsGSwwFZu3aXClDklh
7tXav1otuUwhODeWMSyBgE0X79wUrPBT6SpXFlmtYA0JyuHrlsTicQnUYkoGzfrF
MSPOY9mU2eXgiFrVwYeD2j2G4KG9jNUcQguSjzA3vEpZK9NtTukj3HzQkttGLBb8
if7DtNxHhrkpmHqOzM55c4QbKBvGAFDwqocn0uH0N7qt8I1vC9W4KH//DxSbpZdY
SFpuYdaXCORaAX0VEGMikdChV6k26EjHprPoIQJ7clJjlEiGaOtp IKoGgnOXMF5
6B8Spm7JJ8sULobDDNNvRgstjmABJoLJDa0kPs9WkIJXLIUO12vPLMb05guju0oL
jYkhkMm9o5MUN qjy/A48FgOqbz9bZ/lOvso76N  L4Hhb6MxSPtNnL5GMl7o7pk
r8qPoVOKyc0AEQEAAYkCPAQYAQgAJhYhBMhmHm6U/60WKiqjdXWiNP I ZwaBQJf
EmsQAhsMBQkHhh AAAoJEHWiNP I ZwaMZQQAJg6NCfHpvFfr9c8/odmt/zEXUpx
42eB2tIFaTd/MSu5QI9rXuV6l2naC9dHBStPrpj2acCyvjeFfsxJ9VJjg3ToZH5B
MJ2l2z28wkMiMhZw/mIPecLwEPyaYNY68 gM1XfBB4e3pmMdMdWMa5WZrC5WVwF 
exn84KNqUSmKmkIfU/WC95CfyiVQYcjdj OstFJMSMeg54KZGLJsRPDnWM83HZOk
WZ4yaiUBEExOI0maIMFm1pYH3n lE28IHPq1RZ0r0ci9WrU8uqwU8/T4r2H/1Yd1
a7LsuO61ERI2N7AED9QtI9uH5U8d8dbatK0Xjf2F4Wc5ErRIDzTaS2MZh2aTYKY 
BrBj7clRYzTf/LNeZv6okYkvxYPsudy4MPvjDijnHEsoUph7gx AFG6Co0V3onA/
emH6M9uqUa5CqZ3qZ1N ePWVarevdgsmQwQj649toluk0F7gkZZboM/gqBhh4g9p
V9wEOwAFNzdZTFd16YG/C3ZOpz9Dn8rYe0pq5dePS 4INr5aD6hjj4hDtV9nbzOM
mkZ6xvnnyzHls4FOqcJRHgn4GPxwNo/y5Y9WDqAV6qZ6jpz8n1JZV9KxDjcq0 BI
Mt0zmeZBXaX3/7LDS75dEYL2uCxVAqxftzIal6dF8hOEEJoRXOkgCKC1IY2 iH3J
UOmZxPhE6x7ZQcKO
=IkuM
-----END PGP PUBLIC KEY BLOCK-----"